project_id = "nwweebxwjpycovlpdath"

[functions.send-gym-invitation]
verify_jwt = false

[functions.accept-gym-invitation]
verify_jwt = false

[functions.send-admin-invitation]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.parse-import]
verify_jwt = false
